# ┌────────────────────────────────────────────────┐
# │  _                                             │
# │ | |_ _  _ _ __ _ _ _ __  __ _ _ __  ___ _ _    │
# │ | ' \ || | '_ \ '_| '_ \/ _` | '_ \/ -_) '_|   │
# │ |_||_\_, | .__/_| | .__/\__,_| .__/\___|_|     │
# │      |__/|_|      |_|        |_|               │
# │                                                │
# │ Author: Belmu - https://www.github.com/BelmuTM │
# └────────────────────────────────────────────────┘

source = $HOME/.config/belmu/vars.conf

wallpaper {
    monitor = DP-1
    path = $BELMU_WALLPAPERS/wallpaper_0.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = $BELMU_WALLPAPERS/wallpaper_1.png
    fit_mode = cover
}

splash=false
