# ┌────────────────────────────────────────────────┐
# │    _       _          _            _           │
# │   /_\ _  _| |_ ___ __| |_ __ _ _ _| |_         │
# │  / _ \ || |  _/ _ (_-<  _/ _` | '_|  _|        │
# │ /_/ \_\_,_|\__\___/__/\__\__,_|_|  \__|        │
# │                                                │
# │                                                │
# │ Author: Belmu - https://www.github.com/BelmuTM │
# └────────────────────────────────────────────────┘

source = $HOME/.config/belmu/vars.conf

# Setup XDG for screen sharing and start waypaper and waybar
exec-once = ~/.config/hypr/scripts/xdg.sh

# Start Polkit
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Load GTK settings
exec-once = ~/.config/hypr/scripts/gtk.sh

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Dock
exec-once = ~/.config/nwg-dock-hyprland/launch.sh

# Using hypridle to start hyprlock
exec-once = hypridle

# Hyprpaper
exec-once = hyprpaper

# Hyprsunset
exec = hyprsunset

# Waybar
exec-once = source $BELMU_SCRIPTS/waybar-launch.sh
