# ┌────────────────────────────────────────────────┐
# │   ___        _                                 │
# │  / __|  _ __| |_ ___ _ __                      │
# │ | (_| || (_-<  _/ _ \ '  \                     │
# │  \___\_,_/__/\__\___/_|_|_|                    │
# │                                                │
# │                                                │
# │ Author: Belmu - https://www.github.com/BelmuTM │
# └────────────────────────────────────────────────┘

# Add your additional Hyprland configurations here
# 
# This is an additional key binding 
# bind = $mainMod CTRL, up, workspace, empty
# 
# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

# No Hardware Cursor
# cursor {
#     no_hardware_cursors = false
# }
