# ┌────────────────────────────────────────────────┐
# │  __  __ _                                      │
# │ |  \/  (_)___ __                               │
# │ | |\/| | (_-</ _|                              │
# │ |_|  |_|_/__/\__|                              │
# │                                                │
# │                                                │
# │ Author: Belmu - https://www.github.com/BelmuTM │
# └────────────────────────────────────────────────┘

misc {
    disable_hyprland_logo = truex
    disable_splash_rendering = true
    initial_workspace_tracking = 1
}
