$background = rgb(010000)
$foreground = rgb(dcbfbd)
$color0 = rgb(010000)
$color1 = rgb(9D586A)
$color2 = rgb(938771)
$color3 = rgb(BE6C80)
$color4 = rgb(CE768B)
$color5 = rgb(E17E97)
$color6 = rgb(BFAD8C)
$color7 = rgb(dcbfbd)
$color8 = rgb(9a8584)
$color9 = rgb(9D586A)
$color10 = rgb(938771)
$color11 = rgb(BE6C80)
$color12 = rgb(CE768B)
$color13 = rgb(E17E97)
$color14 = rgb(BFAD8C)
$color15 = rgb(dcbfbd)
