--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/belmu/Images/5zbH8Yq.jpeg"

-- Special
background="#010000"
foreground="#dcbfbd"
cursor="#dcbfbd"

-- Colors
color0="#010000"
color1="#9D586A"
color2="#938771"
color3="#BE6C80"
color4="#CE768B"
color5="#E17E97"
color6="#BFAD8C"
color7="#dcbfbd"
color8="#9a8584"
color9="#9D586A"
color10="#938771"
color11="#BE6C80"
color12="#CE768B"
color13="#E17E97"
color14="#BFAD8C"
color15="#dcbfbd"
