# Shell variables
# Generated by 'wal'
wallpaper='/home/belmu/Images/5zbH8Yq.jpeg'

# Special
background='#010000'
foreground='#dcbfbd'
cursor='#dcbfbd'

# Colors
color0='#010000'
color1='#9D586A'
color2='#938771'
color3='#BE6C80'
color4='#CE768B'
color5='#E17E97'
color6='#BFAD8C'
color7='#dcbfbd'
color8='#9a8584'
color9='#9D586A'
color10='#938771'
color11='#BE6C80'
color12='#CE768B'
color13='#E17E97'
color14='#BFAD8C'
color15='#dcbfbd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
