# ┌────────────────────────────────────────────────┐
# │  _    _                                        │
# │ | |__| |_ ___ _ __                             │
# │ | '_ \  _/ _ \ '_ \                            │
# │ |_.__/\__\___/ .__/                            │
# │              |_|                               │
# │                                                │
# │ Author: Belmu - https://www.github.com/BelmuTM │
# └────────────────────────────────────────────────┘

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#000000"

# Main text color
theme[main_fg]="#E17E97"

# Title color for boxes
theme[title]="#dcbfbd"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#E17E97"

# Background color of selected item in processes box
theme[selected_bg]="#938771"

# Foreground color of selected item in processes box
theme[selected_fg]="#dcbfbd"

# Color of inactive/disabled text
theme[inactive_fg]="#010000"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#BE6C80"

# Background color of the percentage meters
theme[meter_bg]="#938771"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#BFAD8C"

# Cpu box outline color
theme[cpu_box]="#938771"

# Memory/disks box outline color
theme[mem_box]="#938771"

# Net up/down box outline color
theme[net_box]="#938771"

# Processes box outline color
theme[proc_box]="#938771"

# Box divider line and small boxes line color
theme[div_line]="#BE6C80"

# Temperature graph colors
theme[temp_start]="#00ff00"
theme[temp_mid]="#ff9933"
theme[temp_end]="#ff0000"

# CPU graph colors
theme[cpu_start]="#00ff00"
theme[cpu_mid]="#ccff66"
theme[cpu_end]="#ff0000"

# Mem/Disk free meter
theme[free_end]="#00ff00"
theme[free_mid]="#ccff66"
theme[free_start]="#ff0000"

# Mem/Disk cached meter
theme[cached_start]="#00ff00"
theme[cached_mid]="#ccff66"
theme[cached_end]="#ff0000"

# Mem/Disk available meter
theme[available_start]="#ff0000"
theme[available_mid]="#ccff66"
theme[available_end]="#00ff00"

# Mem/Disk used meter
theme[used_start]="#00ff00"
theme[used_mid]="#ccff66"
theme[used_end]="#ff0000"

# Download graph colors
theme[download_start]="#00ff00"
theme[download_mid]="#ff9933"
theme[download_end]="#ff0000"

# Upload graph colors
theme[upload_start]="#00ff00"
theme[upload_mid]="#ff9933"
theme[upload_end]="#ff0000"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#938771"
theme[process_mid]="#BFAD8C"
theme[process_end]="#dcbfbd"
